server:
  port: 8081
  address: 0.0.0.0
  
spring:
  application:
    name: eureka-server
    
eureka:
  instance:
    hostname: ${server.address:0.0.0.0}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"