eureka:
  instance:
    hostname: ${server.address:0.0.0.0}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://${eureka.instance.hostname}:8081/eureka/"
      
management.endpoints.web.exposure.include: "*"
management.endpoints.web.base-path: /actuator

server:
  port: 8084
  address: 0.0.0.0

spring:
  application:
    name: redirect-service